### ISSUE TITLE
Testing Localhost

### ISSUE THREAD

**Issue by Wemago** [HansSchouten/PHPagebuilder-boilerplate#2]
I'm trying to use the page builder on localhost sub folder.

Installed downloading the zip files and removed the http/s from the htaccess.

When I try to go localhost/pagebuilder or localhost/pagebuilder/admin it always gives me page not found.

Tried to debug but haven't found anything.

**Comment by HansSchouten** [comment]
Hi, I noticed I only tested it in a domain's root directory and not in a sub folder like you are doing. I just tried it out and got the same issue. In `.htaccess` the `RewriteBase` line should be removed and a number of methods in the PHPageBuilder package did not handle sub directories correctly. I just fixed this, so now everything should work as expected.

Thanks for your feedback!

**Comment by HansSchouten** [comment]
And FYI, in the updated version your webserver won't give a 404, but the project will still give a "page not found" message. This is because you first need to login via `/admin` and create a homepage with the URL set to: `/`. In later versions I will make this more clear.

**Comment by Wemago** [comment]
For some reason it's still not working.
I've been trying to debug but without success.
I'm using xampp on w10.

So I'm getting this
![php_page_builder](https://user-images.githubusercontent.com/135612/80276288-3d22c180-86d7-11ea-9cd7-c566b4a7370d.png)

on phpb_url I have this, is it supposed to call auth twice?
![phpb_url](https://user-images.githubusercontent.com/135612/80276299-588dcc80-86d7-11ea-9495-9a0c9b8b8b22.png)

and on phpb_current_url I've got this, don't know why but ltrim is not giving the right value.
![phpb_current_url](https://user-images.githubusercontent.com/135612/80276309-74916e00-86d7-11ea-88d5-2ba93c942039.png)

BTW thanks for the fast reply and your work on this script looks amazing!

**Comment by HansSchouten** [comment]
Thanks. The second call to `phpb_in_module('auth')` was not needed, so I removed it. I could replicate your issue, with the same setup. I misunderstood the working of ltrim/rtrim. The second argument is a character set and not the exact substring that will be matched. I pushed a fix to the PHPageBuilder master.

**Comment by Wemago** [comment]
Thanks! It's working.
Do you have a road map? 
Will you be adding the other specs and blocks from grapejs?
 There's a lot of potential here.

**Comment by HansSchouten** [comment]
Glad to hear, thanks for trying out the project in this early phase!

I am planning to further develop this project nearly every day the coming year. I do not have an actual roadmap at the moment since the features I add are currently driven by the needs of the bigger platform I am developing (for complex travel agency websites with advanced search through various external data sources). I just finished of multi-language support and am currently trying out the pagebuilder in practice.

To my knowledge I am not missing much of the features GrapesJS provides, however at the moment all the desired blocks need to be created by the developer using the platform. So you create an html/php block with the desired static/dynamic content, render a thumbnail for the block and start using it. But I can see the benefits of having an extensive demo theme build on bootstrap (with some more complex example blocks), so I am planning to add this together with more extensive documentation in the coming months.

In the meantime feel free to open any ticket or drop by at [https://phpagebuilder.slack.com](https://join.slack.com/t/phpagebuilder/shared_invite/zt-e3o6m1c0-tII6RWY9DU7m0~0XO383Jw) if you need any help.
